export type Problem = {
	id: string;
	title: string;
	difficulty: string;
	category: string;
	order: number;
	videoId?: string;
};

export const problems: Problem[] =  [
	{
		id: "two-sum",
		title: "Two Sum",
		difficulty: "Easy",
		category: "Array",
		order: 1,
		videoId: "BoHO04xVeU0",
	},
	{
		id: "reverse-linked-list",
		title: "Reverse Linked List",
		difficulty: "Hard",
		category: "Linked List",
		order: 2,
		videoId: "",
	},
	{
		id: "jump-game",
		title: "Jump Game",
		difficulty: "Medium",
		category: "Dynamic Programming",
		order: 3,
		videoId: "",
	},
	{
		id: "valid-parentheses",
		title: "Valid Parentheses",
		difficulty: "Easy",
		category: "Stack",
		order: 4,
		videoId: "",
	},
	{
		id: "search-a-2d-matrix",
		title: "Search a 2D Matrix",
		difficulty: "Medium",
		category: "Binary Search",
		order: 5,
		videoId: "",
	},
	{
		id: "container-with-most-water",
		title: "Container With Most Water",
		difficulty: "Medium",
		category: "Two Pointers",
		order: 6,
		videoId: "",
	},
	{
		id: "merge-intervals",
		title: "Merge Intervals",
		difficulty: "Medium",
		category: "intervals",
		order: 7,
		videoId: "",
	},
	{
		id: "maximum-depth-of-binary-tree",
		title: "Maximum Depth of Binary Tree",
		difficulty: "Easy",
		category: "Tree",
		order: 8,
		videoId: "",
	},
	{
		id: "best-time-to-buy-and-sell-stock",
		title: "Best Time to Buy and Sell Stock",
		difficulty: "Easy",
		category: "Array",
		order: 9,
		videoId: "",
	},
	{
		id: "subsets",
		title: "Subsets",
		difficulty: "Medium",
		category: "Backtracking",
		order: 10,
		videoId: "",
	},
    {
        id: "add-two-numbers",
		title: "Add Two Numbers",
		difficulty: "Medium",
		category: "Linked List",
		order: 11,
		videoId: "",
    },
    {
        id: "longest-substring-without-repeating-characters",
		title: "Longest Substring Without Repeating Characters",
		difficulty: "Medium",
		category: "Strings",
		order: 12,
		videoId: "",
    },
    {
        id: "palindrome-number",
		title: "Palindrome Number",
		difficulty: "Easy",
		category: "Math",
		order: 13,
		videoId: "",
    },
    {
        id: "reverse-integer",
		title: "Reverse Integer",
		difficulty: "Medium",
		category: "Math",
		order: 14,
		videoId: "",
    },
    {
        id: "string-to-integer",
		title: "String to Integer (atoi)",
		difficulty: "Medium",
		category: "Strings",
		order: 15,
		videoId: "",
    },
    {
        id: "container-with-most-water",
		title: "Container With Most Water",
		difficulty: "Medium",
		category: "Array",
		order: 16,
		videoId: "",
    },
    {
        id: "integer-to-roman",
		title: "Integer to Roman",
		difficulty: "Medium",
		category: "Math",
		order: 17,
		videoId: "",
    },
    {
        id: "longest-common-prefix",
		title: "Longest Common Prefix",
		difficulty: "Easy",
		category: "Trie",
		order: 18,
		videoId: "",
    },
    {
        id: "longest-vallid-parenthesis",
		title: "Longest Valid Parentheses",
		difficulty: "Hard",
		category: "Stack",
		order: 19,
		videoId: "",
    },
    {
        id: "reverse-nodes-in-k-group",
		title: "Reverse Nodes in k-Group",
		difficulty: "Hard",
		category: "Linked List",
		order: 20,
		videoId: "",
    },
];